### ISSUE TITLE
Colmap based point fusion produces awkward result

### ISSUE THREAD

**Issue by jaymefosa** [nianticlabs/simplerecon#11]
After running colmap and getting the dense undistorted images and camera poses everything seems to be good (including the depth maps) up until the point cloud fusion step. Is there an issue with intrinsics again by any chance?

![image](https://user-images.githubusercontent.com/92468/192078121-dd837099-e0ed-4119-b285-018a01070642.png)

**Comment by pengwangucla** [comment]
I think the fusion doesn't work well if the pose info is not from ground truth. Noise pose can produce in correct fusion

**Comment by mohammed-amr** [comment]
This model is trained on ScanNet images with a the range of FOVs present in their train set. So I'd do two things in this situation:

- Make sure that I'm scaling my COLMAP reconstruction (intrinsics and extrinsics) using the appropriate known absolute world measurement. This is necessary to get a good metric scale estimate out of an MVS method, and since SimpleRecon is trained with metric depth, necessary for a good estimate from the model. This should help https://github.com/colmap/colmap/issues/58 and https://colmap.github.io/faq.html#geo-registration
- Crop my input images and intrinsics matrices to roughly match the FOV of ScanNet images. We've used iPhone images successfully with a ScanNet trained model. You can check the vdr sequences for intrinsics information you can use as a reference.

Thanks for your interest.
